---
- name: apt -- Ensure agent dependencies are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python-apt
      - apt-transport-https

- name: apt -- Add agent repository key
  apt_key:
    url: "{{ threatstack_url }}/APT-GPG-KEY-THREATSTACK"
    id: 6EE04BD4
    validate_certs: "{{ threatstack_pkg_validate | bool }}"

- name: apt -- Add agent repository
  apt_repository:
    repo: "deb {{ threatstack_pkg_url }}/Ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: apt -- Ensure latest agent is installed when no version specified
  set_fact:
    threatstack_pkg: threatstack-agent=2*
  when:
    - threatstack_pkg == 'threatstack-agent'

- name: apt -- Ensure agent is installed
  apt:
    name: "{{ threatstack_pkg }}"
    state: "{{ threatstack_pkg_state }}"
  when: threatstack_pkg_version is not defined

- name: apt -- Ensure agent specified version is installed
  apt:
    name: "{{ threatstack_pkg }}={{threatstack_pkg_version}}"
    state: "{{ threatstack_pkg_state }}"
  when: threatstack_pkg_version is defined

- name: apt -- Stop and disable agent if not configured
  become: yes
  service:
    name: threatstack
    state: stopped
    enabled: no
  when:
    - threatstack_agent_disable_service | bool
