---
- name: Check auditd status
  command: service auditd status
  register: auditd_status
  ignore_errors: true

- name: Stop service auditd
  command: service auditd stop
  when: auditd_status.rc == 0

- name: Disable service auditd
  command: systemctl disable auditd
  when: auditd_status.rc == 0
