---
- name: Ensure ThreatStack repo is installed
  template:
    src: threatstack.j2
    dest: /etc/yum.repos.d/threatstack.repo
    owner: root
    group: root
    mode: 0644

- name: Add ThreatStack repo GPG key
  rpm_key:
    key: "{{ threatstack_url }}/RPM-GPG-KEY-THREATSTACK"
    state: present
    validate_certs: "{{ threatstack_pkg_validate | bool }}"

- name: Ensure 2.x is installed when no version specified
  set_fact:
    threatstack_pkg: threatstack-agent-2*
  when:
    - not threatstack_v1
    - threatstack_pkg == 'threatstack-agent'

- name: Ensure Agent is installed
  yum:
    name: "{{ threatstack_pkg }}"
    state: "{{ threatstack_pkg_state }}"
    update_cache: yes
  when: threatstack_pkg is not defined

- name: Ensure Agent specified version is installed
  yum:
    name: "{{ threatstack_pkg }}-{{threatstack_pkg_version}}"
    state: "{{ threatstack_pkg_state }}"
    update_cache: yes
  when: threatstack_pkg_version is defined

- name: Stop and disable ThreatStack if not configured
  become: yes
  service:
    name: threatstack
    state: stopped
    enabled: no
  when:
    - threatstack_agent_disable_service | bool
